language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
deploy:
  provider: heroku
  api_key:
    secure: tfkMB1jbkzlu/bTwFJoY579JV7fMwCr7yoGDRn2kLq+FBd4q1k5uvQ3KfL3X0ABtzG8HNsoB26m7+AURIxx8+rZAnuyzolu/BfZomp9zKfZggQxOxmiLmj3hlr+63gQpzlNmlfAHbVRMSRT/WDhYskEv1roNFindvqCASBI+x+HrVw1e5eyaGXzPychIjWv8apNTePi1j2Mi6BpuUFRwiSn0OhGBpd+MZcc5OhMrCc0YUjeWHca0W/i8FRrFCDMZHdqLHmz/sTIbTUXvDKCZnaR2vSfUd0kc6OTJzgebJMZP7AwOBsRiz4K5YrDU1LjGW8x30e647oAz/FDwS4IMvs9SbV7zQZkgWZgNaR9FueFNL6wOup6ftiKenQz/vk2itZdpZfXj9I25rhSKwWPDjbwODBBkM1wIFQQAWm54g3fhZs8tZ36/DKJRCcNODj+HrbmE/o0wbWBhqy6bM1dBanSiPFnxDc5LUqgDlhUqHKim0RyG26pKPsZOeAedklDxlwP1Lt38iZSGFv8V/wMvG0fIPFYrhyNvDp/jDfkYhnCOaHi2Sk/vnVkiDJfn9tKX6wmFLjU67Y1tNetjJsfTxqBOV8SvBAjkcQnfMLFamWcIJ5G/+nWaZY7MjZLr3rh98RQhUFWQVIuU1tuL+yLe4iLimXr9TAlac1CKY/BVu+s=
  app: agile-plateau-54162
  on:
    repo: kkindorf/guardian
